<?php

namespace Application\Sonata\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
       public function getLastTen()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a FROM ApplicationSonataMediaBundle:Gallery a ORDER BY a.createdAt DESC')
                        ->setMaxResults(10)
                        ->getResult();
    }

    public function getAllByDate()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a FROM ApplicationSonataMediaBundle:Gallery a ORDER BY a.createdAt DESC')
                        ->getResult();
    }
    
    public function getIdFromSlug($id)
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a.id FROM ApplicationSonataMediaBundle:Gallery a WHERE a.slug = :id'
                        )->setParameter('id', $id)
                        ->getSingleResult();
    }


    public function removePhotographerFromGalleries(\YallaWebsite\BackendBundle\Entity\Photographer $photographer, $galleries)
    {
        foreach ($galleries as $gallery) {
            if ($gallery->hasPhotographer($photographer)) {
                $gallery->removePhotographer($photographer);
            }
        }
    }
}
