imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata_media/sonata_media.yml }
    #- { resource: tinymce/tinymce.yml }
    - { resource: knp_paginator/knp_paginator.yml }
    - { resource: fos_user/fos_user.yml }
    - { resource: sonata_seo/sonata_seo.yml }
    - { resource: fpn_tag/fpn_tag.yml }
    - { resource: gedmo/gedmo.yml }
    - { resource: hwi_oauth/hwi_oauth.yml }
    - { resource: yallawebsite.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    esi: { enabled: true }
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../app/Resources/FOSUserBundle": FOSUserBundle
        "%kernel.root_dir%/../src/YallaWebsite/BackendBundle/Resources": YallaWebsiteBackendBundle
        "%kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources": YallaWebsiteFrontendBundle
        #"%kernel.root_dir%/../app/Resources/ApplicationSonataMediaBundle": SonataMediaBundle

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - YallaWebsiteBackendBundle
        - YallaWebsiteFrontendBundle
        - FOSUserBundle
        - SonataMediaBundle
        - StarRatingBundle
    # java: C:\\Program Files\\Java\\jdk1.8.0_60\\bin\\java.exe
    filters:
#        cssrewrite:
#             apply_to: "\.css$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: ".less$"
    assets:
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css
            #filters: [cssrewrite]
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.js    
        frontend_css:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/less/style.less
            output: "css/style.css"
            filters: [lessphp]
        massonary:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/js/masonry.pkgd.min.js
        imagesloaded:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/js/imagesloaded.pkgd.min.js
        fontawesome_css:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/css/font-awesome.min.css
        fontawesome_css_be:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/BackendBundle/Resources/public/css/font-awesome.css
        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
        century_gothic_boldttf:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/CenturyGothic-Bold/CenturyGothic-Bold.ttf
            output: "fonts/CenturyGothic-Bold.ttf"
        century_gothic_boldeot:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/CenturyGothic-Bold/CenturyGothic-Bold.eot
            output: "fonts/CenturyGothic-Bold.eot"    
        ebrima_ttf:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Ebrima/Ebrima.ttf
            output: "fonts/Ebrima.ttf"
        ebrima_eot:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Ebrima/Ebrima.eot
            output: "fonts/Ebrima.eot"
        ebrima_svg:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Ebrima/Ebrima.svg
            output: "fonts/Ebrima.svg"
        ebrima_woff:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Ebrima/Ebrima.woff
            output: "fonts/Ebrima.woff"
        ebrima_woff2:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Ebrima/Ebrima.woff2
            output: "fonts/Ebrima.woff2"
        awesome_otf:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Awesome/FontAwesome.otf
            output: "fonts/fontawesome-webfont.otf"
        awesome_eot:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Awesome/webfont.eot
            output: "fonts/fontawesome-webfont.eot"
        awesome_svg:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Awesome/webfont.svg
            output: "fonts/fontawesome-webfont.svg"
        awesome_ttf:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Awesome/webfont.ttf
            output: "fonts/fontawesome-webfont.ttf"
        awesome_woff:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Awesome/webfont.woff
            output: "fonts/fontawesome-webfont.woff"
        awesome_woff2:
            inputs:
                - %kernel.root_dir%/../src/YallaWebsite/FrontendBundle/Resources/public/fonts/Awesome/webfont.woff2
            output: "fonts/fontawesome-webfont.woff2"
        

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                #naming_strategy: doctrine.orm.naming_strategy.default
                auto_mapping: true
#                mappings:
#                    YallaWebsiteFrontendBundle: ~
#                    YallaWebsiteBackendBundle: ~
#                    DCSTagBundle: ~
                dql:
                    datetime_functions:
                        dayofweek:     Luxifer\DQL\Datetime\DayOfWeek
                        year:     Luxifer\DQL\Datetime\Year
                        Day:     Luxifer\DQL\Datetime\Day
                        month:     Luxifer\DQL\Datetime\Month

# Doctrine migrations
#doctrine_migrations:
#    dir_name: "%kernel.root_dir%/DoctrineMigrations"
#    namespace: Application\Migrations
#    table_name: migration_versions
#    name: Application Migrations
    
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
    
kunstmaan_voting:
    actions:
        up_vote:
            default_value: 1
        down_vote:
            default_value: -1
        facebook_like:
            default_value: 1
        facebook_send:
            default_value: 1
        linkedin_share:
            default_value: 1