sonata_seo:
    sitemap:
        services:
            - app.custom_sitemap_service

        doctrine_orm:
             # gallery
            - { types: [image], connection: doctrine.dbal.default_connection, route: sonata_media_view,       parameters: {id: null},                               query: "SELECT id, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM media__media WHERE enabled = true" }
            # article
#            - { group: "article",  connection: doctrine.dbal.default_connection, route: sonata_news_view,        parameters: {permalink: null},                        query: "SELECT CONCAT_WS('/', YEAR(created_at), MONTH(created_at), DAY(created_at), slug) as permalink , updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM news__post WHERE enabled = 1 AND (publication_date_start IS NULL OR publication_date_start <= NOW())" }
#            # page - works only for one site, please adapt the code if required
#            - {                 connection: doctrine.dbal.default_connection, route: page_slug,               parameters: {path: null},                             query: "SELECT url as path, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM page__snapshot WHERE route_name = 'page_slug' AND enabled = 1 AND (publication_date_start IS NULL OR publication_date_start <= NOW())" }
#            # product categories
#            - {                 connection: doctrine.dbal.default_connection, route: sonata_catalog_category, parameters: {category_id: null, category_slug: null}, query: "SELECT id as category_id, slug as category_slug, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM classification__category WHERE enabled = true" }
#            # products
            - {                 connection: doctrine.dbal.default_connection, route: backend_article_show,     parameters: {productId: null },            query: "SELECT id as productId,  updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM article" }
    encoding:         UTF-8
    page:
        default: sonata.seo.page.default
        title:            Yalla Night Life
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             artists, venues. events, galleries, images, nigh, life, night life
                description:          yalla night life website for all new events in egypt
                developer:	Michel Khater, m.f.khater@gmail.com
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':         YallaNightLife
                'og:description':       YallaNightLife Website.
                #'og:see_also' :         http://www.yallanightlife.com/
#                'og:url' :
#                'og:image' :
                'og:type' :             website
                #'twitter:card':         yalla night life website for all new events in egypt
                #'twitter:url' :         http://www.yallanightlife.com/
                #'twitter:title' :       http://www.yallanightlife.com/
                'twitter:description':  yalla night life website for all new events in egypt

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                'Content-Language':     en-us
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':                http://www.w3.org/1999/xhtml
            'xmlns:og':             http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"
#            'prefix':
            'itemscope itemtype':   http://schema.org/WebPage
