hwi_oauth:
    connect:
        account_connector: my_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: secured_area
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           516228625234128
            client_secret:       41990cb594420495744dd2e0aa378657
            scope:               "email"
            infos_url:          "https://graph.facebook.com/me?fields=id,name,email"
            paths:
                email:          email