<?php

namespace YallaWebsite\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    public function findBySlug($id)
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a FROM YallaWebsiteBackendBundle:Article a WHERE a.slug = :id'
                        )->setParameter('id', $id)
                        ->getSingleResult();
    }

    public function getLastTen()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a FROM YallaWebsiteBackendBundle:Article a ORDER BY a.createdAt DESC')
                        ->setMaxResults(10)
                        ->getResult();
    }
    
    
    public function getLastAll()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a FROM YallaWebsiteBackendBundle:Article a ORDER BY a.createdAt DESC')
                        ->getResult();
    }

}
