<?php

namespace YallaWebsite\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VenueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenueRepository extends EntityRepository
{
    public function getLastTen()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a FROM YallaWebsiteBackendBundle:Venue a ORDER BY a.createdAt DESC')
                        ->setMaxResults(20)
                        ->getResult();
    }
    
       public function getLastAll()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a FROM YallaWebsiteBackendBundle:Venue a ORDER BY a.createdAt DESC')
                        ->getResult();
    }

}
