backend_event_index:
    path:   /
    defaults:  { _controller: YallaWebsiteBackendBundle:Event:index }

backend_event_new:
    path:   /new
    defaults:  { _controller: YallaWebsiteBackendBundle:Event:new }

backend_event_create:
    path:   /create
    defaults:  { _controller: YallaWebsiteBackendBundle:Event:create }


backend_event_show:
    path:   /show/{id}
    defaults:  { _controller: YallaWebsiteBackendBundle:Event:show }
    requirements: 
          id: \d+
          
backend_event_edit:
    path:   /edit/{id}
    defaults:  { _controller: YallaWebsiteBackendBundle:Event:edit }
    requirements: 
          id: \d+

backend_event_save:
    path: /save
    defaults:  { _controller: YallaWebsiteBackendBundle:Event:update }    

backend_event_delete:
    path: /delete/{id}
    defaults:  { _controller: YallaWebsiteBackendBundle:Event:delete }
    requirements: 
          id: \d+
